# -*- coding: utf-8 -*-
"""Workshop1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bxt9Cw9TR1u_KW7ZESQTg58le-n9vFOj

# WORKSHOP 1

#1) Display Fibonacci series up to 10 terms.
"""

# Fibonacci series up to 10 terms

n = 10
a, b = 0, 1

print("Fibonacci Series:")

for i in range(n):
    print(a, end=" ")
    a, b = b, a + b

"""#2) Find the factorial of a given number. Ask the user to provide the number.

"""

# Factorial Program

num = int(input("Enter a number: "))
factorial = 1

if num < 0:
    print("Factorial does not exist for negative numbers")
elif num == 0:
    print("Factorial of 0 is 1")
else:
    for i in range(1, num + 1):
        factorial *= i
    print("Factorial of", num, "is", factorial)

"""#3) Write a program to print a right angle triangle using the for loop.

"""

# Right angle triangle

rows = int(input("Enter number of rows: "))

for i in range(1, rows + 1):
    print("*" * i)

"""#4) Make a simple calculator that can add, subtract, multiply and divide two numbers using function.

"""

# Calculator using functions

def add(a, b):
    return a + b

def subtract(a, b):
    return a - b

def multiply(a, b):
    return a * b

def divide(a, b):
    if b == 0:
        return "Cannot divide by zero"
    return a / b

num1 = float(input("Enter first number: "))
num2 = float(input("Enter second number: "))
operation = input("Enter operation (+, -, *, /): ")

if operation == "+":
    print("Result:", add(num1, num2))
elif operation == "-":
    print("Result:", subtract(num1, num2))
elif operation == "*":
    print("Result:", multiply(num1, num2))
elif operation == "/":
    print("Result:", divide(num1, num2))
else:
    print("Invalid operation")

"""#5) Remove the first duplicate element of a list"""

# Remove first duplicate element

my_list = [1, 2, 3, 2, 4, 5]

for i in range(len(my_list)):
    if my_list[i] in my_list[i+1:]:
        del my_list[i]
        break

print("Updated list:", my_list)

"""#6) Write a Python program to create a new dictionary by extracting the mentioned keys from the below dictionary"""

sample_dict = {
    "name": "namuna",
    "age": 35,
    "salary": 5000,
    "city": "London"
}

keys = ["name", "salary"]

new_dict = {}

for key in keys:
    if key in sample_dict:
        new_dict[key] = sample_dict[key]

print(new_dict)

"""#7) Write a Python program to convert two lists into a dictionary in a way that item from list_one is the key and item from list_two is the value.

"""

list_one = ['one', 'two', 'three']
list_two = [1, 2, 3]

result = {}

for i in range(len(list_one)):
    result[list_one[i]] = list_two[i]

print(result)